## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
import shutil

def build(bld):
    module = bld.create_ns3_module('wasmfaas', ["applications"])
    module.includes = '.'

    module.source = [
        'model/custom-app.cc',
        'helper/custom-app-helper.cc'
    ]

    headers = bld(features='ns3header')
    headers.module = 'wasmfaas'
    headers.source = [
        'model/custom-app.h',
        'model/libwasmfaas.h',
        'helper/custom-app-helper.h'
        ]


def configure(conf):
    lib_to_check = 'libwasmfaas.so'
    conf.env.append_value("LINKFLAGS", ["-Lcommon"])
    conf.env.append_value("LIB", ["wasmfaas"])  
